backend:
  replicaCount: 1
  image:
    repository: springcommunity/spring-petclinic-rest
    tag: latest
    
frontend:
  image:
    repository: nginx
    tag: latest

postgresql:
  auth:
    username: petclinic
    password: petclinicpass
    database: petclinic
  primary:
    persistence:
      enabled: true
      size: 1Gi