backend:
  replicaCount: 1
  image:
    repository: kennethreitz/httpbin
    tag: latest
  resources:
    requests:
      cpu: "25m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "64Mi"

frontend:
  replicaCount: 1
  image:
    repository: nginx
    tag: latest
  resources:
    requests:
      cpu: "20m"
      memory: "24Mi"
    limits:
      cpu: "80m"
      memory: "48Mi"
  apiPath: "/prod-api/get"

postgresql:
  auth:
    username: petclinic
    password: petclinicpass
    database: petclinic
  primary:
    persistence:
      enabled: true
      size: 1Gi

ingress:
  mode: path