apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  DB_HOST: {{ printf "%s-postgresql" .Release.Name | quote }}
  DB_PORT: "5432"
  SPRING_PROFILES_ACTIVE: "postgres,spring-data-jpa"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ printf "%s-postgresql" .Release.Name }}:5432/{{ .Values.postgresql.auth.database }}"