apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parcial1.fullname" . }}-db
type: Opaque
stringData:
  DB_USER: {{ .Values.postgresql.auth.username | quote }}
  DB_PASS: {{ .Values.postgresql.auth.password | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}